import { MigrationInterface, QueryRunner, Table } from "typeorm";

export class CreateErpOrderHeaderTable1694304518341 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: "order_header",
        columns: [
          { name: "id", type: "int", isGenerated: true, generationStrategy: "increment", isPrimary: true },
          { name: "otherrefnum", type: "varchar", length: "20" },
          { name: "tranid", type: "varchar", length: "20" },
          { name: "custbody_sw_PRT＿ORDNO", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CST_PO_NO", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "trandate", type: "date", isNullable: true, default: null },
          { name: "custbody_sw_jv_INS_CAT_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_jv_GP_ID", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_ORD_NM", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_ORD_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_ORD_TEL_NO", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_ORD_PIC_EMAIL", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_ORD_PIC", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_ORD_ADR", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_ACC_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_ACC_TEL_NO", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_ACC_PIC_EMAIL", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_ACC_PIC", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_ACC_ADR", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CST_RNK", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CSG_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CSG_NM", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CSG_TEL_NO", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CSG_PIC_EMAIL", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CSG_PIC", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CSG_ADR", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_jv_SHP_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_jv_SHP_NM", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_jv_SHP_TEL_NO", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_jv_SHP_PIC_EMAIL", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_jv_SHP_PIC", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_jv_SHP_ADR", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_jv_SHP_CMT", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_jv_SHP_CONTACT_DT", type: "timestamp", isNullable: true, default: null },
          { name: "custbody_sw_jv_SHP_CONTACT_FG", type: "smallint", isNullable: true, default: null },
          { name: "custbody_sw_jv_CST_FWD_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_jv_CST_FWD_NM", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_jv_QOT_NO", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_jv_QOT_PIC", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_jv_QOT_ISU_DT", type: "timestamp", isNullable: true, default: null },
          { name: "custbody_sw_jv_QOT_EXP_DT", type: "timestamp", isNullable: true, default: null },
          { name: "custbody_sw_SHP_VSL_NO", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_SHP_CO_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_SHP_EST_DT", type: "timestamp", isNullable: true, default: null },
          { name: "custbody_sw_RORO_CONT_ID", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_voyage", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_vessel_company", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_DEP_PORT_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_ETD", type: "timestamp", isNullable: true, default: null },
          { name: "custbody_sw_ARV_PORT_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_ETA", type: "timestamp", isNullable: true, default: null },
          { name: "custbody_sw_forwarder", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_BL_NO", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_BL_DT", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_BL_CFM_FG", type: "smallint", isNullable: true, default: null },
          { name: "custbody_sw_CONT_NO", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_SEAL_NO", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CST_SHP_NM", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CST_DEP_PORT_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CST_ARV_PORT_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CST_DEST_CNT_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CST_VIN_NO", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CST_MAK_DESC", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CST_MDL_DESC", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CST_GRD_DESC", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CST_ENG_NO", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CST_HS_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CST_COLOR_DESC", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CST_AUCGRD_DESC", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_jv_RQS_INS_DT_FR", type: "timestamp", isNullable: true, default: null },
          { name: "custbody_sw_jv_RQS_INS_DT_TO", type: "timestamp", isNullable: true, default: null },
          { name: "custbody_sw_jv_RQS_INS_FLD_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_jv_RQS_ARA_CD", type: "varchar", length: "255", isNullable: true, default: null },
          // { name: "custbody_sw_jv_RQS_INS_FLD_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_jv_ORI_ARA_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "shipaddresslist", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "shipaddress", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_VIN_NO", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_MAK_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_MDL_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_GRD_DESC", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_COLOR", type: "varchar", length: "255", isNullable: true, default: null },
          // { name: "custbody_sw_MDL_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_ENGINE_MDL_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CAR_TYP_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CAR_OBJ_DESC", type: "varchar", length: "255", isNullable: true, default: null },
          // { name: "custbody_sw_CAR_TYP_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CAR_SHAPE", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_CAR_CC", type: "int", isNullable: true, default: null },
          { name: "custbody_sw_CAR_FUEL", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_PSG_CAP_NO", type: "int", isNullable: true, default: null },
          { name: "custbody_sw_INT_REG_DT", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_MANUF_YR", type: "int", isNullable: true, default: null },
          { name: "custbody_sw_LEN", type: "int", isNullable: true, default: null },
          { name: "custbody_sw_HGT", type: "int", isNullable: true, default: null },
          { name: "custbody_sw_WDT", type: "int", isNullable: true, default: null },
          { name: "custbody_sw_M2", type: "int", isNullable: true, default: null },
          { name: "custbody_sw_M3", type: "int", isNullable: true, default: null },
          { name: "custbody_sw_NET_WGT", type: "int", isNullable: true, default: null },
          { name: "custbody_sw_GRS_WGT", type: "int", isNullable: true, default: null },
          { name: "custbody_sw_LIGHTCAR_FG", type: "smallint", isNullable: true, default: null },
          { name: "custbody_sw_TRUCK_FG", type: "smallint", isNullable: true, default: null },
          { name: "custbody_sw_AIRIS_CHK_FG", type: "smallint", isNullable: true, default: null },
          { name: "custbody_sw_AIRIS_CHK_DT", type: "timestamp", isNullable: true, default: null },
          { name: "custbody_sw_AIRS_SRC_KEY", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_AIRIS_NOT_EXS_FG", type: "smallint", isNullable: true, default: null },
          { name: "custbody_sw_LVIS_CHK_FG", type: "smallint", isNullable: true, default: null },
          { name: "custbody_sw_LVIS_CHK_DT", type: "timestamp", isNullable: true, default: null },
          { name: "custbody_sw_LVIS_NOT_EXS_FG", type: "smallint", isNullable: true, default: null },
          { name: "custbody_sw_RCL_CHK_DT", type: "timestamp", isNullable: true, default: null },
          { name: "custbody_sw_RCL_FG", type: "smallint", isNullable: true, default: null },
          { name: "custbody_sw_RCL_CHK_RST_DT", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_RCL_NOTI_DT", type: "timestamp", isNullable: true, default: null },
          { name: "custbody_sw_RCL_OWNER_POLICY", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_RCL_ACT_DT", type: "timestamp", isNullable: true, default: null },
          { name: "custbody_sw_RCL_ACT_CONTENTS", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_YRD_IN_DT", type: "timestamp", isNullable: true, default: null },
          { name: "custbody_sw_YRD_IN_CD", type: "varchar", length: "255", isNullable: true, default: null },
          { name: "custbody_sw_INR_CRG_FG", type: "smallint", isNullable: true, default: null },
          { name: "created_by", type: "int", isNullable: true, default: null },
          { name: "updated_by", type: "int", isNullable: true, default: null },
          { name: "created_at", type: "timestamp", default: "now()" },
          { name: "updated_at", type: "timestamp", default: "now()" },
        ],
      }),
      true,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable("order_header");
  }
}
