version: "3.9"

services:
  api:
    build: .
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5433
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin@2023
      POSTGRES_DB: jenesis
    volumes:
      - ./.data/db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./.data/redis:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6380
    ports:
      - "8081:8081"
    depends_on:
      - redis
